using UnityEngine;

public class ElevatorSlideXYZ : MonoBehaviour
{
    [Header("Positions")]
    public Vector3 pointA;   // Position Ø§Ù„Ø¨Ø¯Ø§ÙŠØ©
    public Vector3 pointB;   // Position Ø§Ù„Ù†Ù‡Ø§ÙŠØ©

    [Header("Rotations (X Y Z)")]
    public Vector3 rotationA; // Rotation Ø§Ù„Ø¨Ø¯Ø§ÙŠØ©
    public Vector3 rotationB; // Rotation Ø§Ù„Ù†Ù‡Ø§ÙŠØ©

    [Header("Speed")]
    public float moveSpeed = 2f;
    public float rotateSpeed = 120f;

    private bool isMoving = false;

    void Start()
    {
        // Ù†Ø«Ø¨Øª Ù†Ù‚Ø·Ø© Ø§Ù„Ø¨Ø¯Ø§ÙŠØ©
        transform.position = pointA;
        transform.rotation = Quaternion.Euler(rotationA);
    }

    void Update()
    {
        if (!isMoving) return;

        // ğŸ”¹ Ø§Ù„Ø­Ø±ÙƒØ©
        transform.position = Vector3.MoveTowards(
            transform.position,
            pointB,
            moveSpeed * Time.deltaTime
        );

        // ğŸ”¹ Ø§Ù„Ø¯ÙˆØ±Ø§Ù† (X Y Z)
        transform.rotation = Quaternion.RotateTowards(
            transform.rotation,
            Quaternion.Euler(rotationB),
            rotateSpeed * Time.deltaTime
        );

        // â›” ÙŠÙˆÙ‚Ù Ø¹Ù†Ø¯ Ø§Ù„ÙˆØµÙˆÙ„
        if (
            Vector3.Distance(transform.position, pointB) < 0.05f &&
            Quaternion.Angle(transform.rotation, Quaternion.Euler(rotationB)) < 0.5f
        )
        {
            isMoving = false;
        }
    }

    // ÙŠÙ†Ø§Ø¯ÙŠÙ‡Ø§ Ø²Ø± E
    public void StartMove()
    {
        isMoving = true;
    }
}
